"""Assemble the vLLM v0.23.0 Windows cu128 wheel without recompiling."""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import os
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = Path(os.environ.get("VLLM_WHEEL_SOURCE", ROOT / "vllm-source")).resolve()
OUT_DIR = Path(os.environ.get("VLLM_WHEEL_OUTPUT", ROOT / "dist-v6")).resolve()
VERSION = "0.23.0+cu128"
PYTHON_TAG = "cp313"
ABI_TAG = "cp313"
PLATFORM_TAG = "win_amd64"
DIST_NAME = "vllm"
DIST_INFO = f"{DIST_NAME}-{VERSION}.dist-info"
WHEEL = OUT_DIR / f"{DIST_NAME}-{VERSION}-{PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}.whl"

SKIP_DIRS = {"__pycache__"}
SKIP_SUFFIXES = {".pyc", ".pyo"}
REQUIRED_FILES = [
    "vllm/_C.pyd",
    "vllm/_C_stable_libtorch.pyd",
    "vllm/_moe_C.pyd",
    "vllm/cumem_allocator.pyd",
    "vllm/spinloop.pyd",
    "vllm/vllm_flash_attn/_vllm_fa2_C.pyd",
    "vllm/vllm-rs.exe",
    "vllm.egg-info/PKG-INFO",
    "vllm.egg-info/entry_points.txt",
    "vllm.egg-info/top_level.txt",
    "LICENSE",
]


def digest(data: bytes) -> str:
    encoded = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    return "sha256=" + encoded.decode("ascii")


def version_py() -> bytes:
    return f"""# Generated by assemble_wheel_cu128_v0.23.0.py
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = {VERSION!r}
__version_tuple__ = version_tuple = (0, 23, 0, "cu128")

__commit_id__ = commit_id = None
""".encode("utf-8")


def wheel_file() -> bytes:
    return (
        "Wheel-Version: 1.0\n"
        "Generator: assemble_wheel_cu128_v0.23.0.py\n"
        "Root-Is-Purelib: false\n"
        f"Tag: {PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}\n"
    ).encode("utf-8")


def package_files() -> list[Path]:
    files: list[Path] = []
    root = SRC / "vllm"
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(SRC).parts):
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue
        files.append(path)
    return sorted(files, key=lambda p: p.as_posix().lower())


def rel(path: Path) -> str:
    return path.relative_to(SRC).as_posix()


def main() -> int:
    missing = [name for name in REQUIRED_FILES if not (SRC / name).exists()]
    if missing:
        for name in missing:
            print(f"ERROR: missing required file: {SRC / name}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if WHEEL.exists():
        WHEEL.unlink()

    records: list[tuple[str, str, int]] = []

    def write(zout: zipfile.ZipFile, arc: str, data: bytes) -> None:
        zout.writestr(arc, data)
        records.append((arc, digest(data), len(data)))

    with zipfile.ZipFile(WHEEL, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zout:
        count = 0
        for path in package_files():
            arc = rel(path)
            data = version_py() if arc == "vllm/_version.py" else path.read_bytes()
            write(zout, arc, data)
            count += 1

        write(zout, f"{DIST_INFO}/METADATA", (SRC / "vllm.egg-info/PKG-INFO").read_bytes())
        write(zout, f"{DIST_INFO}/WHEEL", wheel_file())
        write(
            zout,
            f"{DIST_INFO}/entry_points.txt",
            (SRC / "vllm.egg-info/entry_points.txt").read_bytes(),
        )
        write(
            zout,
            f"{DIST_INFO}/top_level.txt",
            (SRC / "vllm.egg-info/top_level.txt").read_bytes(),
        )
        write(zout, f"{DIST_INFO}/licenses/LICENSE", (SRC / "LICENSE").read_bytes())

        record = io.StringIO()
        writer = csv.writer(record, lineterminator="\n")
        for arc, file_digest, size in records:
            writer.writerow([arc, file_digest, str(size)])
        writer.writerow([f"{DIST_INFO}/RECORD", "", ""])
        zout.writestr(f"{DIST_INFO}/RECORD", record.getvalue().encode("utf-8"))

    print(f"package files : {count}")
    print(f"wheel         : {WHEEL}")
    print(f"size          : {WHEEL.stat().st_size / 1e6:.1f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
