"""Assemble the vLLM v0.24.0 Windows cu128 wheel without recompiling."""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import os
import sys
import zipfile
from collections import Counter
from email.parser import BytesParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = Path(os.environ.get("VLLM_WHEEL_SOURCE", ROOT / "vllm-source")).resolve()
OUT_DIR = Path(os.environ.get("VLLM_WHEEL_OUTPUT", ROOT / "dist-v8")).resolve()
FLASH_ATTN_SRC = Path(
    os.environ.get(
        "VLLM_FLASH_ATTN_SOURCE",
        SRC / ".deps" / "vllm-flash-attn-src",
    )
).resolve()
VERSION = "0.24.0+cu128"
PYTHON_TAG = "cp313"
ABI_TAG = "cp313"
PLATFORM_TAG = "win_amd64"
DIST_NAME = "vllm"
DIST_INFO = f"{DIST_NAME}-{VERSION}.dist-info"
WHEEL = OUT_DIR / f"{DIST_NAME}-{VERSION}-{PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}.whl"

SKIP_DIRS = {"__pycache__"}
SKIP_SUFFIXES = {".pyc", ".pyo"}
REQUIRED_FILES = [
    "vllm/_C_stable_libtorch.pyd",
    "vllm/_moe_C_stable_libtorch.pyd",
    "vllm/_rust_tool_parser.pyd",
    "vllm/cumem_allocator.pyd",
    "vllm/spinloop.pyd",
    "vllm/vllm_flash_attn/_vllm_fa2_C.pyd",
    "vllm/vllm-rs.exe",
    "vllm/third_party/triton_kernels",
    "vllm/third_party/fmha_sm100",
    "vllm.egg-info/PKG-INFO",
    "vllm.egg-info/entry_points.txt",
    "vllm.egg-info/top_level.txt",
    "LICENSE",
]
REQUIRED_ARCHIVE_FILES = {
    "vllm/v1/simple_kv_offload/cuda_mem_ops.py",
    "vllm/v1/worker/gpu/sample/states.py",
    "vllm/vllm_flash_attn/layers/__init__.py",
    "vllm/vllm_flash_attn/layers/rotary.py",
    "vllm/vllm_flash_attn/ops/__init__.py",
    "vllm/vllm_flash_attn/ops/triton/__init__.py",
    "vllm/vllm_flash_attn/ops/triton/rotary.py",
    "vllm/vllm_flash_attn/cute/__init__.py",
    "vllm/vllm_flash_attn/cute/interface.py",
}

REQUIRED_NONEMPTY_FILES = {
    "vllm/_C_stable_libtorch.pyd",
    "vllm/_moe_C_stable_libtorch.pyd",
    "vllm/_rust_tool_parser.pyd",
    "vllm/cumem_allocator.pyd",
    "vllm/spinloop.pyd",
    "vllm/vllm_flash_attn/_vllm_fa2_C.pyd",
    "vllm/vllm-rs.exe",
}

SAMPLING_STATES = "vllm/v1/worker/gpu/sample/states.py"
INT64_SEED_FIX = b"_NP_INT64_MIN, _NP_INT64_MAX, dtype=np.int64"
KV_OFFLOAD_DMA = "vllm/v1/simple_kv_offload/cuda_mem_ops.py"
WINDOWS_KV_OFFLOAD_FIX = b'if sys.platform == "win32":\n        _copy_blocks_windows'
WINDOWS_KV_OFFLOAD_COPY = b"(err,) = cudart.cudaMemcpyAsync("


def digest(data: bytes) -> str:
    encoded = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    return "sha256=" + encoded.decode("ascii")


def version_py() -> bytes:
    return f"""# Generated by assemble_wheel_cu128_v0.24.0.py
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = {VERSION!r}
__version_tuple__ = version_tuple = (0, 24, 0, "cu128")

__commit_id__ = commit_id = None
""".encode("utf-8")


def wheel_file() -> bytes:
    return (
        "Wheel-Version: 1.0\n"
        "Generator: assemble_wheel_cu128_v0.24.0.py\n"
        "Root-Is-Purelib: false\n"
        f"Tag: {PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}\n"
    ).encode("utf-8")


def package_files() -> list[Path]:
    files: list[Path] = []
    root = SRC / "vllm"
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(SRC).parts):
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue
        files.append(path)
    return sorted(files, key=lambda p: p.as_posix().lower())


def generated_flash_attn_files() -> dict[str, Path | bytes]:
    """Return Python payloads generated by vllm-flash-attn's CMake install."""
    entries: dict[str, Path | bytes] = {}
    package_root = FLASH_ATTN_SRC / "vllm_flash_attn"
    if package_root.is_dir():
        for path in package_root.rglob("*.py"):
            relative = path.relative_to(package_root).as_posix()
            if relative in {"__init__.py", "flash_attn_interface.py"}:
                continue
            entries[f"vllm/vllm_flash_attn/{relative}"] = path

    cute_root = FLASH_ATTN_SRC / "flash_attn" / "cute"
    if cute_root.is_dir():
        for path in cute_root.rglob("*.py"):
            relative = path.relative_to(cute_root).as_posix()
            data = path.read_bytes().replace(
                b"flash_attn.cute", b"vllm.vllm_flash_attn.cute"
            )
            entries[f"vllm/vllm_flash_attn/cute/{relative}"] = data
    return entries


def archive_entries() -> dict[str, Path | bytes]:
    entries: dict[str, Path | bytes] = {}
    for path in package_files():
        arc = rel(path)
        entries[arc] = version_py() if arc == "vllm/_version.py" else path
    for arc, payload in generated_flash_attn_files().items():
        entries.setdefault(arc, payload)
    return entries


def rel(path: Path) -> str:
    return path.relative_to(SRC).as_posix()


def validate_source() -> list[str]:
    errors: list[str] = []
    for name in REQUIRED_FILES:
        path = SRC / name
        if not path.exists():
            errors.append(f"missing required path: {path}")
        elif path.is_dir() and not any(item.is_file() for item in path.rglob("*")):
            errors.append(f"required directory is empty: {path}")
    for name in REQUIRED_NONEMPTY_FILES:
        path = SRC / name
        if path.is_file() and path.stat().st_size == 0:
            errors.append(f"required binary is empty: {path}")

    sampling_states = SRC / SAMPLING_STATES
    if not sampling_states.is_file():
        errors.append(f"missing sampling state source: {sampling_states}")
    elif INT64_SEED_FIX not in sampling_states.read_bytes():
        errors.append(
            "sampling seed generation does not request np.int64; "
            "the wheel would fail on Windows"
        )

    kv_offload_dma = SRC / KV_OFFLOAD_DMA
    if not kv_offload_dma.is_file():
        errors.append(f"missing Windows KV-offload source: {kv_offload_dma}")
    else:
        kv_offload_data = kv_offload_dma.read_bytes()
        if (
            WINDOWS_KV_OFFLOAD_FIX not in kv_offload_data
            or WINDOWS_KV_OFFLOAD_COPY not in kv_offload_data
        ):
            errors.append(
                "simple KV offload does not contain the Windows "
                "cudaMemcpyAsync fallback"
            )

    metadata_path = SRC / "vllm.egg-info" / "PKG-INFO"
    if metadata_path.is_file():
        metadata = BytesParser().parsebytes(metadata_path.read_bytes())
        if metadata.get("Name", "").lower() != DIST_NAME:
            errors.append(f"metadata Name is {metadata.get('Name')!r}, expected {DIST_NAME!r}")
        if metadata.get("Version") != VERSION:
            errors.append(
                f"metadata Version is {metadata.get('Version')!r}, expected {VERSION!r}"
            )
    return errors


def validate_wheel(path: Path) -> None:
    with zipfile.ZipFile(path) as wheel:
        bad_member = wheel.testzip()
        if bad_member:
            raise ValueError(f"ZIP CRC check failed: {bad_member}")

        names = wheel.namelist()
        duplicates = [name for name, count in Counter(names).items() if count > 1]
        if duplicates:
            raise ValueError(f"duplicate archive members: {sorted(duplicates)}")

        missing = REQUIRED_ARCHIVE_FILES - set(names)
        if missing:
            raise ValueError(f"missing required wheel payloads: {sorted(missing)}")

        if INT64_SEED_FIX not in wheel.read(SAMPLING_STATES):
            raise ValueError("wheel is missing the Windows int64 sampling-seed fix")
        kv_offload_data = wheel.read(KV_OFFLOAD_DMA)
        if (
            WINDOWS_KV_OFFLOAD_FIX not in kv_offload_data
            or WINDOWS_KV_OFFLOAD_COPY not in kv_offload_data
        ):
            raise ValueError("wheel is missing the Windows KV-offload DMA fallback")

        cute_files = [
            name
            for name in names
            if name.startswith("vllm/vllm_flash_attn/cute/") and name.endswith(".py")
        ]
        if len(cute_files) < 40:
            raise ValueError(f"incomplete CuteDSL payload: {len(cute_files)} files")
        for name in cute_files:
            data = wheel.read(name).replace(b"vllm.vllm_flash_attn.cute", b"")
            if b"flash_attn.cute" in data:
                raise ValueError(f"unrewritten CuteDSL import: {name}")

        metadata_name = f"{DIST_INFO}/METADATA"
        metadata = BytesParser().parsebytes(wheel.read(metadata_name))
        if metadata.get("Name", "").lower() != DIST_NAME:
            raise ValueError(f"wheel metadata has invalid Name: {metadata.get('Name')!r}")
        if metadata.get("Version") != VERSION:
            raise ValueError(f"wheel metadata has invalid Version: {metadata.get('Version')!r}")

        record_name = f"{DIST_INFO}/RECORD"
        rows = {
            row[0]: (row[1], row[2])
            for row in csv.reader(io.StringIO(wheel.read(record_name).decode("utf-8")))
        }
        if set(rows) != set(names):
            raise ValueError("RECORD does not cover every archive member")
        for name in names:
            file_digest, size = rows[name]
            if name == record_name:
                if file_digest or size:
                    raise ValueError("RECORD must not hash itself")
                continue
            data = wheel.read(name)
            if file_digest != digest(data) or size != str(len(data)):
                raise ValueError(f"invalid RECORD entry: {name}")


def main() -> int:
    source_errors = validate_source()
    if source_errors:
        for error in source_errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    entries = archive_entries()
    missing_archive_files = sorted(REQUIRED_ARCHIVE_FILES - entries.keys())
    if missing_archive_files:
        for name in missing_archive_files:
            print(f"ERROR: missing required wheel payload: {name}", file=sys.stderr)
        print(f"FlashAttention source checked at: {FLASH_ATTN_SRC}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if WHEEL.exists():
        WHEEL.unlink()

    records: list[tuple[str, str, int]] = []

    def write(zout: zipfile.ZipFile, arc: str, data: bytes) -> None:
        zout.writestr(arc, data)
        records.append((arc, digest(data), len(data)))

    with zipfile.ZipFile(WHEEL, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zout:
        for arc, payload in sorted(entries.items()):
            data = payload.read_bytes() if isinstance(payload, Path) else payload
            write(zout, arc, data)

        write(zout, f"{DIST_INFO}/METADATA", (SRC / "vllm.egg-info/PKG-INFO").read_bytes())
        write(zout, f"{DIST_INFO}/WHEEL", wheel_file())
        write(
            zout,
            f"{DIST_INFO}/entry_points.txt",
            (SRC / "vllm.egg-info/entry_points.txt").read_bytes(),
        )
        write(
            zout,
            f"{DIST_INFO}/top_level.txt",
            (SRC / "vllm.egg-info/top_level.txt").read_bytes(),
        )
        write(zout, f"{DIST_INFO}/licenses/LICENSE", (SRC / "LICENSE").read_bytes())

        record = io.StringIO()
        writer = csv.writer(record, lineterminator="\n")
        for arc, file_digest, size in records:
            writer.writerow([arc, file_digest, str(size)])
        writer.writerow([f"{DIST_INFO}/RECORD", "", ""])
        zout.writestr(f"{DIST_INFO}/RECORD", record.getvalue().encode("utf-8"))

    try:
        validate_wheel(WHEEL)
    except (OSError, KeyError, ValueError, zipfile.BadZipFile) as exc:
        print(f"ERROR: assembled wheel validation failed: {exc}", file=sys.stderr)
        WHEEL.unlink(missing_ok=True)
        return 1

    print(f"package files : {len(entries)}")
    print(f"flash-attn src: {FLASH_ATTN_SRC}")
    print(f"wheel         : {WHEEL}")
    print(f"size          : {WHEEL.stat().st_size / 1e6:.1f} MB")
    print("validation    : passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
