"""Assemble the vLLM v0.24.0 Windows cu128 wheel without recompiling."""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import os
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = Path(os.environ.get("VLLM_WHEEL_SOURCE", ROOT / "vllm-source")).resolve()
OUT_DIR = Path(os.environ.get("VLLM_WHEEL_OUTPUT", ROOT / "dist-v8")).resolve()
FLASH_ATTN_SRC = Path(
    os.environ.get(
        "VLLM_FLASH_ATTN_SOURCE",
        SRC / ".deps" / "vllm-flash-attn-src",
    )
).resolve()
VERSION = "0.24.0+cu128"
PYTHON_TAG = "cp313"
ABI_TAG = "cp313"
PLATFORM_TAG = "win_amd64"
DIST_NAME = "vllm"
DIST_INFO = f"{DIST_NAME}-{VERSION}.dist-info"
WHEEL = OUT_DIR / f"{DIST_NAME}-{VERSION}-{PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}.whl"

SKIP_DIRS = {"__pycache__"}
SKIP_SUFFIXES = {".pyc", ".pyo"}
REQUIRED_FILES = [
    "vllm/_C_stable_libtorch.pyd",
    "vllm/_moe_C_stable_libtorch.pyd",
    "vllm/_rust_tool_parser.pyd",
    "vllm/cumem_allocator.pyd",
    "vllm/spinloop.pyd",
    "vllm/vllm_flash_attn/_vllm_fa2_C.pyd",
    "vllm/vllm-rs.exe",
    "vllm/third_party/triton_kernels",
    "vllm/third_party/fmha_sm100",
    "vllm.egg-info/PKG-INFO",
    "vllm.egg-info/entry_points.txt",
    "vllm.egg-info/top_level.txt",
    "LICENSE",
]
REQUIRED_ARCHIVE_FILES = {
    "vllm/vllm_flash_attn/layers/rotary.py",
    "vllm/vllm_flash_attn/ops/triton/rotary.py",
    "vllm/vllm_flash_attn/cute/__init__.py",
    "vllm/vllm_flash_attn/cute/interface.py",
}


def digest(data: bytes) -> str:
    encoded = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    return "sha256=" + encoded.decode("ascii")


def version_py() -> bytes:
    return f"""# Generated by assemble_wheel_cu128_v0.24.0.py
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = {VERSION!r}
__version_tuple__ = version_tuple = (0, 24, 0, "cu128")

__commit_id__ = commit_id = None
""".encode("utf-8")


def wheel_file() -> bytes:
    return (
        "Wheel-Version: 1.0\n"
        "Generator: assemble_wheel_cu128_v0.24.0.py\n"
        "Root-Is-Purelib: false\n"
        f"Tag: {PYTHON_TAG}-{ABI_TAG}-{PLATFORM_TAG}\n"
    ).encode("utf-8")


def package_files() -> list[Path]:
    files: list[Path] = []
    root = SRC / "vllm"
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(SRC).parts):
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue
        files.append(path)
    return sorted(files, key=lambda p: p.as_posix().lower())


def generated_flash_attn_files() -> dict[str, Path | bytes]:
    """Return Python payloads generated by vllm-flash-attn's CMake install."""
    entries: dict[str, Path | bytes] = {}
    package_root = FLASH_ATTN_SRC / "vllm_flash_attn"
    if package_root.is_dir():
        for path in package_root.rglob("*.py"):
            relative = path.relative_to(package_root).as_posix()
            if relative in {"__init__.py", "flash_attn_interface.py"}:
                continue
            entries[f"vllm/vllm_flash_attn/{relative}"] = path

    cute_root = FLASH_ATTN_SRC / "flash_attn" / "cute"
    if cute_root.is_dir():
        for path in cute_root.rglob("*.py"):
            relative = path.relative_to(cute_root).as_posix()
            data = path.read_bytes().replace(
                b"flash_attn.cute", b"vllm.vllm_flash_attn.cute"
            )
            entries[f"vllm/vllm_flash_attn/cute/{relative}"] = data
    return entries


def archive_entries() -> dict[str, Path | bytes]:
    entries: dict[str, Path | bytes] = {}
    for path in package_files():
        arc = rel(path)
        entries[arc] = version_py() if arc == "vllm/_version.py" else path
    for arc, payload in generated_flash_attn_files().items():
        entries.setdefault(arc, payload)
    return entries


def rel(path: Path) -> str:
    return path.relative_to(SRC).as_posix()


def main() -> int:
    missing = [name for name in REQUIRED_FILES if not (SRC / name).exists()]
    if missing:
        for name in missing:
            print(f"ERROR: missing required file: {SRC / name}", file=sys.stderr)
        return 1

    entries = archive_entries()
    missing_archive_files = sorted(REQUIRED_ARCHIVE_FILES - entries.keys())
    if missing_archive_files:
        for name in missing_archive_files:
            print(f"ERROR: missing required wheel payload: {name}", file=sys.stderr)
        print(f"FlashAttention source checked at: {FLASH_ATTN_SRC}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if WHEEL.exists():
        WHEEL.unlink()

    records: list[tuple[str, str, int]] = []

    def write(zout: zipfile.ZipFile, arc: str, data: bytes) -> None:
        zout.writestr(arc, data)
        records.append((arc, digest(data), len(data)))

    with zipfile.ZipFile(WHEEL, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zout:
        for arc, payload in sorted(entries.items()):
            data = payload.read_bytes() if isinstance(payload, Path) else payload
            write(zout, arc, data)

        write(zout, f"{DIST_INFO}/METADATA", (SRC / "vllm.egg-info/PKG-INFO").read_bytes())
        write(zout, f"{DIST_INFO}/WHEEL", wheel_file())
        write(
            zout,
            f"{DIST_INFO}/entry_points.txt",
            (SRC / "vllm.egg-info/entry_points.txt").read_bytes(),
        )
        write(
            zout,
            f"{DIST_INFO}/top_level.txt",
            (SRC / "vllm.egg-info/top_level.txt").read_bytes(),
        )
        write(zout, f"{DIST_INFO}/licenses/LICENSE", (SRC / "LICENSE").read_bytes())

        record = io.StringIO()
        writer = csv.writer(record, lineterminator="\n")
        for arc, file_digest, size in records:
            writer.writerow([arc, file_digest, str(size)])
        writer.writerow([f"{DIST_INFO}/RECORD", "", ""])
        zout.writestr(f"{DIST_INFO}/RECORD", record.getvalue().encode("utf-8"))

    print(f"package files : {len(entries)}")
    print(f"flash-attn src: {FLASH_ATTN_SRC}")
    print(f"wheel         : {WHEEL}")
    print(f"size          : {WHEEL.stat().st_size / 1e6:.1f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
